<section class="search">
    <div class="search__form">
        <form action="/user/search" method="POST">
            <input class="search__input" type="text" name="usuario" id="usuario" placeholder="Quem você esta procurando?" aria-label="usuario">
    
            <button class="search__btn" type="submit">Procurar</button>
        </form>
    </div>

<?php if (isset($pendentes)) { foreach($pendentes as $pendente) { ?>

    <div class="search__item">
        <p><?= $pendente->nome ?></p>

        <div>
            <a class="search__link search__link--follow" href="/user/confirm/<?= $pendente->iduser ?>">Confirmar</a>
        </div>
    </div>
<?php }} ?>
    
<?php if (isset($results)) { foreach($results as $user) { if ($user->status != 'amigos') { ?>

    <div class="search__item">
        <p><?= $user->nome ?></p>

        <div>
            <a class="search__link search__link--follow" href="/user/follow/<?= $user->iduser ?>">Adicionar</a>

            <!-- <a class="search__link search__link--unfollow" href="/user/unfollow/<?= $user->iduser ?>">Deixar de seguir</a> -->
        </div>
    </div>

<?php }}} ?>

</section>